version: "3.1"
services:
  postgres:
    image: "mdillon/postgis:9.6"
    ports:
      - "3232:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
